# Generated by Django 4.2.12 on 2024-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_stock_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_in_date',
            field=models.DateTimeField(),
        ),
    ]
