# Generated by Django 4.2.12 on 2024-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_stock_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_in_date',
            field=models.CharField(max_length=255),
        ),
    ]
